[tools]
node = "25.3"
pnpm = "10.28"

[tasks.check]
description = "全てのコマンドをチェックする"
run = [
  "pnpm run typecheck",
  "pnpm run format",
  "pnpm run lint",
  "pnpm run test:coverage",
  "pnpm run build"
]
